### ISSUE TITLE
sjsdm_cv Gpu not enabled

### ISSUE THREAD

**Issue by CaiWang0503** [TheoreticalEcology/s-jSDM#100]
Hi,
I am running "SJSDM_CV" on Kaggle, but the monitor shows that it is not running with GPU, but "SJSDM" can run with GPU. I wonder if "SJSDM_CV" needs some time to load data and then enable GPU, or it's an error. (I already gave it the parameter device = "gpu"
<img width="214" alt="Screenshot 2022-05-01 at 08 15 22" src="https://user-images.githubusercontent.com/48045062/166136787-6c76756c-7053-47bf-ab79-f6d8bc581b6b.png">
)

**Comment by MaximilianPi** [comment]
Hi, 
okay, that's weird
Please try again with n_gpu = 1 (and device = "gpu") as argument in sjSDM_cv

**Comment by CaiWang0503** [comment]
it looks like a memory issue
it said: "Your notebook tried to allocate more memory than is available" (it works well 2 month ago, so i am not sure if it's kaggle's problem)

but my dataset is very small (250 sites and 15 species),
i have tried n_gpu = 1 and n_core=1, it still show the same issue.
is that the new version's problem or just because kaggle not suit for it now.
looks like i can't use it at the moment

**Comment by MaximilianPi** [comment]
does it run on the CPU?

**Comment by CaiWang0503** [comment]
it didn't use a lot of GPU like before, most of time i saw it only uses CPU, and GPU is used very occasionally...maybe is Kaggle's problem
