### ISSUE TITLE
incorrect mean evaluation metrics in short_summary from sjSDM_cv.R ?

### ISSUE THREAD

**Issue by Cdevenish** [TheoreticalEcology/s-jSDM#104]
In Lines 259 - 267 of sjSDM_cv.R
```
  res = data.frame(tune_step = 1:nrow(tune_samples), 
                   AUC_test = rep(NA,nrow(tune_samples)),
                   AUC_test_macro = rep(NA,nrow(tune_samples)),
                   logLik = rep(NA,nrow(tune_samples)))
  
  for(t in 1:nrow(tune_samples)) {
      res[t,2] = mean(summary_results$AUC_macro_test[summary_results$iter == t])
      res[t,3] = mean(summary_results$AUC_train[summary_results$iter == t])
      res[t,4] = sum(summary_results$ll_test[summary_results$iter == t])

```
seems like the mean values of the evaluation metrics across the folds for each tune grid row are mixed up: 
AUC_test in the short summary is actually mean AUC_macro_test
AUC_test_macro is AUC_train

This will have implications in choosing the best tuning parameters using `plot.sjSDM_cv`

**Comment by MaximilianPi** [comment]
Hi @Cdevenish,
yes, you are right, it is a bug that is mostly affects the best parameters selected by the plot.sjSDM_cv when  'AUC' is used as test metric. Thanks for reporting. I will push a fix and prepare a new CRAN version.
