### ISSUE TITLE
Co-occurrence matrix based on residual associations

### ISSUE THREAD

**Issue by WevertonBio** [TheoreticalEcology/s-jSDM#106]
Hi,

Is there a way to get residual associations among the species (i.e, the matrix that describe co-occurrence patterns that are not explained by environmental filtering) from model?

Thanks!

**Comment by MaximilianPi** [comment]
Hi @WevertonBio,

Yes:
```
getCov(model) 
# usually we normalize it to the correlation matrix:
# cov2cor(getCov(model))
```
