### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) : torch._C._LinAlgError: linalg.inv: The diagonal element 1 is zero

### ISSUE THREAD

**Issue by Samyar1400** [TheoreticalEcology/s-jSDM#112]
Hi Everyone
First of all, Dear Max, Thank you so much for answering my previous question in previous post.

Dear friends,  when I run the sjSDM function I got this error.

Iter: 100/100 100%|██████████| [07:55,  4.76s/it, loss=75.196]

Calculating standard errors...
Species: 0/27   0%|          | [00:04, ?it/s]
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  torch._C._LinAlgError: linalg.inv: The diagonal element 1 is zero, the inversion could not be completed because the input matrix is singular.

Could anyone help me to solve the problem?
Thank you very much
Regards
Jalil

**Comment by MaximilianPi** [comment]
Hi @Samyar1400,

It seems to be a numerical issue, here two things you could try:

1. change` sjSDM(..., dtype="float64")`
2. set a very weak l2 regularization just to help with the optimization: `sjSDM(..., env = linear(..., lambda = 0.001), spatial = linear(...., lambda = 0.001))`

Did you scale all of your variables?
