### ISSUE TITLE
plotInternalStructure: there is no package called ‘ggplodt2’

### ISSUE THREAD

**Issue by WevertonBio** [TheoreticalEcology/s-jSDM#118]
Hello,

I installed the package's development version today. When I use the plotInternalStructure function, I get the following error:
`Error in loadNamespace(x) : there is no package called ‘ggplodt2’`

I believe it is due to a typo in the anova function (line 503 in https://github.com/TheoreticalEcology/s-jSDM/blob/master/sjSDM/R/anova.R):
`ggplodt2::theme(tern.axis.arrow.text = element_text(size = 7),legend.position = "bottom", legend.margin = margin(r = 30), legend.box="vertical")`

**Comment by MaximilianPi** [comment]
Thx @WevertonBio!
