### ISSUE TITLE
plotInternalStructure error

### ISSUE THREAD

**Issue by agnes-duhamet** [TheoreticalEcology/s-jSDM#123]
Hi,
I have a problem with the plotInternalStructure function with my anova.
When I try to run this:  results = plotInternalStructure(anova_5)
I have the error: Error in data.frame(env = ifelse(x$sites[[type]]$A < 0, 0, x$sites[[type]]$A),  : 
arguments imply different numbers of lines : 0, 460
I don't understand where this error came from.
Here is my anova file:
[anova_5.zip](https://github.com/TheoreticalEcology/s-jSDM/files/11831537/anova_5.zip)

Thanks in advance for your help,

Agnès

**Comment by MaximilianPi** [comment]
Hi @agnes-duhamet ,
Good that the problem is solved. What was the problem? It worked on my computer.
Max

**Comment by agnes-duhamet** [comment]
I try this in an other computer and it works (That's why I closed the issue). So I don't understand why it doesn't work on my computer 
Error:  Error in data.frame(env = ifelse(x$sites[[type]]$A < 0, 0, x$sites[[type]]$A), : arguments imply different numbers of lines : 0, 460

**Comment by MaximilianPi** [comment]
Do you have an old version of sjSDM on the other computer?

**Comment by agnes-duhamet** [comment]
I do think it's a problem with the version. I ran the model and the anova on a more powerful computer with version 1.0.5 of sjSDM and on my computer I only had version 1.0.4. Now that I have installed version 1.0.5 on my computer the function works. 
Thanks
