### ISSUE TITLE
VENN diagram Anova

### ISSUE THREAD

**Issue by agnes-duhamet** [TheoreticalEcology/s-jSDM#129]
Hi,
I don't understand how to interpret Venn diagram plot after Anova. I understand that the numbers are the R2 McFadden but what does the numbers between Environment and Association, Association and Spatial, and between Spatial and Environement mean ? Is it **interaction** between Environment and Association, Association and Spatial and between Spatial and Environment ?
Thanks in advance,

Agnès

**Comment by florianhartig** [comment]
Hello Agnès,

I'm very sorry for the late reply. The intersects of the components are the so-called shared components. This is a general problem in ANOVA, related to the discussion about Typ I, II, III and so forth. See, e.g., here https://theoreticalecology.github.io/AdvancedRegressionModels/2B-ANOVA.html

Best,
Florian
