### ISSUE TITLE
Python install

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/s-jSDM#13]
Hi, Max, I just removed the link that didn't work in https://github.com/TheoreticalEcology/s-jSDM/commit/fc6fb9b9bcab4a4adf503c2dee45914b77780285

Does the rest of the pip stuff work (e.g. pip install sjSDM_py), or was this changed now that the code is in the package?

**Comment by MaximilianPi** [comment]
Thanks! I will work on the documentation now. The stand-alone pip package should work. 
The R package doesn't install the sjSDM_py via pip anymore.
