### ISSUE TITLE
sjSDM_model - hide or push?

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/s-jSDM#21]
At the moment, sjSDM_model is only / mostly? used internally to build the model. I wonder - is it distracting to have this open, and should we rather hide it? If we're not hiding it, I would add it a bit more prominently to the help and link it to other functions.

**Comment by MaximilianPi** [comment]
sjSDM_model is the base model class for the DNN (keras style) API:

```
com = simulate_SDM(env = 3L, species = 5L, sites = 100L)
X = com$env_weights
Y = com$response

# the activation function in the last layer must be linear (NULL)
model = sjSDM_model(input_shape = 3L)
model %>% 
  layer_dense(units = 10L, activation = "tanh") %>% 
  layer_dense(units = 10L, activation = "relu") %>% 
  layer_dense(units = 5L) 

model %>% 
  compile(df = 50L, 
          optimizer = optimizer_adamax(learning_rate = 0.01), 
          l1_cov = 0.0001, 
          l2_cov = 0.0001)

model %>% 
  summary

model %>% 
  fit(X = X, Y = Y, epochs = 10L, batch_size = 10L)

# species association matrix:
sp = getCov(model)

# you can also continue training:
model %>% 
  fit(X = X, Y = Y, epochs = 10L, batch_size = 10L)
```

There is also a section in the vignette for this model class.  We could add a reference in the sjSDM detail section... and maybe we should rename the model, e.g. to sjSDM_DNN?

**Comment by florianhartig** [comment]
hmm ... but in principle, you can use create all types of models with that, right? I just wonder how much sense it makes to have this for most users, but on the other hand, it can't hurt to have it, so I would just leave it and suggest to close

**Comment by MaximilianPi** [comment]
Well, because of the api changes (flexible linear/dnn structures, and using PyTorch nn.modules) the implementation of this approach is not so easy anymore, which is why I removed it for now (there are other more important things to do for now). I will close this.
