### ISSUE TITLE
Model_sjSDM object has no attribute 'set_weights'

### ISSUE THREAD

**Issue by frmunoz** [TheoreticalEcology/s-jSDM#28]
I get the following error :

```
pred = predict(model, test_X)
  # Error in py_get_attr_impl(x, name, silent) : 
  # AttributeError: 'Model_sjSDM' object has no attribute 'set_weights'
```

Indeed model has an attribute weights, but not an attribute set_weights.

**Comment by MaximilianPi** [comment]
Thanks for reporting! 
When a model is loaded from disk, the model is initialized and the weights have to be set to the trained weights. 
There were bugs in the python core and and in R initialization function: 7207617e2dce8ae82571b635c97997719afbeeca (I added a few tests to cover this functionality, which should have been done earlier...)

Fetching the latest version should resolve this bug now (sorry for the inconvenience)

**Comment by MaximilianPi** [comment]
I assume that the predict function is now working properly
