### ISSUE TITLE
Install "private" conda version?

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/s-jSDM#30]
Hi Max, just a follow-up to #23 - Now at least it works from a clean (= conda-free) computer. One thing that I am wondering - what happens if a user already has a conda version on their computer? At the moment, you are trying to use it, right? 

Wouldn't it be safer to always install a dedicated "private" miniconda version for sjSDM?

**Comment by MaximilianPi** [comment]
Yes, at the moment we first check if we can use an available conda.

> Wouldn't it be safer to always install a dedicated "private" miniconda version for sjSDM?

I do not think that is a good idea:
1. I am not sure how reticulate manages several conda installations. If we install miniconda along another conda installation reticulate might still use the other original conda installation. 
2. I wouldn't want this (as a user)... loss of control, memory, etc.

**Comment by MaximilianPi** [comment]
I will close this for now... let see how people cope with the current installation
