### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by MaximilianPi** [TheoreticalEcology/s-jSDM#35]
Vignettes should answer/cover (derived from user question):
- [ ] how to evaluate model fit?
- [ ] which learning rate should I choose?
- [ ] what about model selection?

Anything to add? @florianhartig

**Comment by florianhartig** [comment]
Well, I suppose we should also explain when to use which structure, etc ... I think it becomes more clear once we write it

**Comment by florianhartig** [comment]
I would not finalize it at the moment though, because the interface is still somewhat changing, maybe make some bullet points / comments, and then let's finalize if we have the feeling the interface is reasonably stable.
