### ISSUE TITLE
sjSDM_cv() Error in unserialize(node$con) : error reading from connection

### ISSUE THREAD

**Issue by dougwyu** [TheoreticalEcology/s-jSDM#36]
I get a weird error running sjSDM_cv().  I'm using R 4.0.0.  my students are running R 3.6.3 and are able to run the test cod e and also on their dataset.

so i'm wondering if it's an R 4 thing.  

```
# sjSDM_cv()
# simulate sparse community:
com = simulate_SDM(env = 5L, species = 25L, sites = 100L, sparse = 0.5)

# tune regularization:
tune_results = sjSDM_cv(Y = com$response,
                        env = com$env_weights, 
                        tune = "random", # random steps in tune-paramter space
                        CV = 3L, # 3-fold cross validation
                        tune_steps = 25L,
                        alpha_cov = seq(0, 1, 0.1),
                        alpha_coef = seq(0, 1, 0.1),
                        lambda_cov = seq(0, 0.1, 0.001), 
                        lambda_coef = seq(0, 0.1, 0.001),
                        n_cores = 2L, # small models can be also run in parallel on the GPU
                        iter = 2L # we can pass arguments to sjSDM via ...
                        )

Error in unserialize(node$con) : error reading from connection
```

**Comment by MaximilianPi** [comment]
Hi Doug, 
this seems to be caused by the 'parallel' pkg (tuning steps are parallelized in sjSDM_cv). I will upgrade one of my systems to R4.0 and get to the bottom of this.
But for now you can turn off the parallelization in sjSDM_cv by setting n_cores=NULL (and it should hopefully work).

**Comment by dougwyu** [comment]
and...it works!  (although with `n_cores = NULL`, R is using six cores)

**Comment by MaximilianPi** [comment]
Yes and no, pytorch should always use all of your cpu cores, but sometimes (if you have really small models) it is efficient to parallelize additionally over the pytorch models from within R 😅

**Comment by dougwyu** [comment]
ah.
