### ISSUE TITLE
Install error sh: line 1: 79672 Killed: 9

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/s-jSDM#48]
Some users get error messages such as the following during install

```
sh: line 1: 79672 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/m_/zb7c8p_13k59p3zrpw84c4hm0000gq/T//Rtmpc0CxFQ/file13725537e4ec1'
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/sjSDM’
Warning in install.packages :
  installation of package ‘/Users/pedro/Desktop/sjSDM_0.0.6.9000.tar.gz’ had non-zero exit status​
```

**Comment by florianhartig** [comment]
We do not understand why the problem occurs, but in the past, it helped to install via 

`install.packages("<path to tar.gz>/sjSDM_0.0.2.9000.tar.gz", repos=NULL, INSTALL_opts = "--no-test-load")`

**Comment by prperes** [comment]
That worked.  Note though, that after I installed the package and run the model I got the following error: 

<div class="bg-gray">
Error in py_call_impl(callable, dots$args, dots$keywords) : 
TypeError: 'NoneType' object is not callable 
</div>

After quitting R and reloading the package, it seems to be working fine now.

**Comment by prperes** [comment]
That worked. Note though, that after I installed the package and run the model I got the following error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : TypeError: 'NoneType' object is not callable
```
After quitting R and reloading the package, it seems to be working fine now.
