### ISSUE TITLE
Register importance and possibly other functions as S3 classes

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/s-jSDM#49]
Just running through Pedro's example, while having run RF before, I noted that if you load the RandomForest package before, this will create a problem 

```
> imp = importance(model)
Error in UseMethod("importance") : 
  no applicable method for 'importance' applied to an object of class "c('sjSDM', 'linear')"
```

because RF registers importance as S3 class. Because of this, I think it would be safer to register all reasonably general sounding functions as S3 classes, or else use names such as sjSDM_importance (but I would prefer the former)

**Comment by MaximilianPi** [comment]
That was unfortunate. The funny thing is that ranger and randomForest are also overwriting each other. I assume that we will change the name of the function in the near future and the problem will be solved on its own.

And most methods are already registered as S3 methods.
