### ISSUE TITLE
Various issues / questions about the installation

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/s-jSDM#5]
For me, 

```
install_sjSDM()
install_sjSDM(method = "auto")
```

produces error 

`Error in install_sjSDM() : object 'package' not found`

Also, https://github.com/TheoreticalEcology/s-jSDM#install-instructions doesn't seem to be up to date

**Comment by MaximilianPi** [comment]
installation via conda is still buggy

**Comment by florianhartig** [comment]
It's probably not possible to consider all issues that could occur. What I would do is to make sure that we have an error message always and directs to help (I think we have this), and add in the help, maybe even in the error message, that people should create an issue here in case they have a problem. This will reduce frustration, and also, we will get an idea about what the typical problems are.

Maybe you should add the think with deleting the environments though, as this could be a frequent problem.
