### ISSUE TITLE
summary how to display the covariance/correlation matrix

### ISSUE THREAD

**Issue by MaximilianPi** [TheoreticalEcology/s-jSDM#53]
We discussed it a few days ago but I only remembered it AFTER the latest PR. So it will go into the next PR:
- Show the full matrix instead of the L
- Question: covariance or correlation matrix?

**Comment by mtva0001** [comment]
Hi! 

Is it possible now to extract the correlation matrix for network visualisation?

Thanks!

**Comment by MaximilianPi** [comment]
Hi, 
yes, the getCov(model) function will extract the covariance matrix. Use cov2cor to get the correlation matrix:

`correlation_matrix = cov2cor(getCov(model))`

**Comment by mtva0001** [comment]
Thank you!

**Comment by MaximilianPi** [comment]
There's now a new method getCor to directly extract the species-species correlation matrix from the fitted model
