### ISSUE TITLE
dependency installation issue in 0.1.8 - missing madgrad

### ISSUE THREAD

**Issue by kjmtaylor22** [TheoreticalEcology/s-jSDM#71]
I reinstalled s-jSDM this morning to get the `importance` update. Loading the package gave this readout:

── Attaching sjSDM ──────────────────────────────────────────────────── 0.1.8 ──
✔ torch 
✔ torch_optimizer 
✔ pyro 
✖ madgrad 

Torch or other dependencies not found:
	1. Use install_sjSDM() to install Pytorch and conda automatically 
	2. Installation trouble shooting guide: ?installation_help 
	3. If 1) and 2) did not help, please create an issue on <https://github.com/TheoreticalEcology/s-jSDM/issues> (see ?install_diagnostic) 

I tried install_sjSDM() with `version = "cpu"` which successfully added madgrad, but removed pyro. I also tried `version = c("cpu","gpu")` and `version = "gpu"` but that didn't change anything. `install_sjSDM()` says that all requirements are satisfied, including pyro, but the package still won't load successfully.

**Comment by MaximilianPi** [comment]
Could you pls post the output of sjSDM::install_diagnostic() here? 

One solution could be to do a clean reinstall:
1. remove the old environment completely:
   i) reticulate::conda_remove("r-reticulate")
   ii) restart session
2. reinstall via install_sjSDM()

I think the installation is still the bottleneck of the package and we have to find a way to improve it

**Comment by kjmtaylor22** [comment]
Ok, yeah I'll give that a go.

> install_diagnostic()

          name
1 r-reticulate
                                                                 python
1 /home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate/bin/python



ENV: r-reticulate


torch:
# packages in environment at /home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate:
#
# Name                    Version                   Build  Channel
pytorch                   1.4.0               py3.6_cpu_0  [cpuonly]  pytorch
pytorch-ranger            0.1.1                    pypi_0    pypi
torch                     1.9.0                    pypi_0    pypi
torch-optimizer           0.1.0                    pypi_0    pypi
torchaudio                0.4.0                      py36    pytorch
torchvision               0.5.0                  py36_cpu  [cpuonly]  pytorch


numpy:
# packages in environment at /home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate:
#
# Name                    Version                   Build  Channel
numpy                     1.19.5           py36h2aa4a07_1    conda-forge


python:         /home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate/bin/python
libpython:      /home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.6m.so
pythonhome:     /home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate:/home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate
version:        3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)  [GCC 7.3.0]
numpy:          /home/k.taylor2/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.5




     active environment : None
       user config file : /home/k.taylor2/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/k.taylor2/.local/share/r-miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/k.taylor2/.local/share/r-miniconda/pkgs
                          /home/k.taylor2/.conda/pkgs
       envs directories : /home/k.taylor2/.local/share/r-miniconda/envs
                          /home/k.taylor2/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Linux/3.10.0-1062.18.1.el7.x86_64 ubuntu/18.04.5 glibc/2.27
                UID:GID : 4967:4034
             netrc file : None
           offline mode : False

**Comment by kjmtaylor22** [comment]
Ok, it took some finagling, but the clean re-install (after `reticulate::conda_remove("r-reticulate")` AND `remove.packages("sjSDM")` seemed to work.

**Comment by MaximilianPi** [comment]
Great! Let's keep this issue open for other users with the same issue when upgrading to version 0.1.8
