### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by drhammed** [TheoreticalEcology/s-jSDM#77]
Hello,

I am trying to fit a model using the sjSDM function. However, I get this error anytime I run the code- "Error in py_call_impl(callable, dots$args, dots$keywords) :  RuntimeError: inverse_cpu: U(1,1) is zero, singular U". 

My species consist of 'presence-absence" data. The error message seems the data is not invertible (i.e. they are likely collinear). Any idea on how to solve this error of singularity? I'll appreciate your kind help. 

Please see the code snipet below.

```
model <- sjSDM(Y = as.matrix(bird_pres_abs[ ,-c(1, 2)]), 
               env = linear(data = bird_bioclim, formula = ~ bio1+bio19), 
               spatial = linear(data = bird_pres_abs, formula = ~ 0+Longitude.x.: Latitude.y.), 
               se = T, family = binomial('probit'), sampling = 100L, device = "cpu")
```

I hope to hear from you soon. 

Thanks,
Hammed

**Comment by MaximilianPi** [comment]
Hi Hammed,
I think it is caused by a dimensional mismatch, can you please post here the output of:
```
dim( as.matrix(bird_pres_abs[ ,-c(1, 2)]) )
dim( bird_bioclim )
dim( bird_pres_abs )

print( linear(data = bird_bioclim, formula = ~ bio1+bio19)$X )
print( linear(data = bird_pres_abs, formula = ~ 0+Longitude.x.: Latitude.y.)$X )
```

**Comment by drhammed** [comment]
Hi Max, 

Thanks for your response. As requested, the outputs are below. 

`dim( as.matrix(bird_pres_abs[ ,-c(1, 2)]) )`

156 311

`dim( bird_bioclim )`

156  19

`dim( bird_pres_abs )`

156 313


`print( linear(data = bird_bioclim, formula = ~ bio1+bio19)$X )`

    (Intercept) bio1 bio19
1             1  -52    58
2             1  -51    55
4             1  -43    64
5             1  -43    64
6             1  -42    62
7             1  -44    63
8             1  -43    63
9             1  -41    61
13            1  -29    68

..... 164

`print( linear(data = bird_pres_abs, formula = ~ 0+Longitude.x.: Latitude.y.)$X )`

    Longitude.x.:Latitude.y.
1                   -5056.75
2                   -5000.25
4                   -5022.75
5                   -4967.25
6                   -4911.75
7                   -4856.25
8                   -4800.75
9                   -4745.25
13                  -5041.25

...164 

I hope to hear from you soon. 

Thanks

**Comment by MaximilianPi** [comment]
Hi Hammed,

the error occurs when the model tries to calculate the coefficients' standard errors. Your predictors are on a very large scale (spatial predictors) which results in very small coefficients (<1e-10) and thus in numerical instabilities when inverting the hessian. Just scale your spatial, or even better, all of your predictors, and the issue should be solved:
```

model <- sjSDM(Y = as.matrix(bird_pres_abs[ ,-c(1, 2)]), 
               env = linear(data = scale(bird_bioclim), formula = ~ bio1+bio19), 
               spatial = linear(data = scale(bird_pres_abs), formula = ~ 0+Longitude.x.: Latitude.y.), 
               se = T, family = binomial('probit'), sampling = 100L, device = "cpu")
```

**Comment by drhammed** [comment]
Thank you so much, Max- that solved it truly.
