### ISSUE TITLE
Arguments for call are not valid. (torch.tensordot)

### ISSUE THREAD

**Issue by benjamindeneu** [TheoreticalEcology/s-jSDM#80]
Hi,
Running the basic example of the python library i got this error when calling build:
`
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  tensordot(Tensor a, Tensor b, int dims=2, Tensor? out=None) -> (Tensor):
  Expected a value of type 'int' for argument 'dims' but instead found type 'List[int]'.
  
  tensordot(Tensor a, Tensor b, (int[], int[]) dims, Tensor? out=None) -> (Tensor):
  Expected a value of type 'Tuple[List[int], List[int]]' for argument 'dims' but instead found type 'List[int]'.
  
  tensordot(Tensor a, Tensor b, int[][] dims, Tensor? out=None) -> (Tensor):
  Expected a value of type 'List[List[int]]' for argument 'dims' but instead found type 'List[int]'.
  
  tensordot(Tensor a, Tensor b, Tensor dims, Tensor? out=None) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'dims' but instead found type 'List[int]'.

The original call is:
  File ".local/lib/python3.7/site-packages/sjSDM_py/model_sjSDM.py", line 747
                def tmp(mu: torch.Tensor, Ys: torch.Tensor, sigma: torch.Tensor, batch_size: int, sampling: int, df: int, alpha: float, device: str, dtype: torch.dtype):
                    noise = torch.randn(size = [sampling, batch_size, df], device=torch.device(device), dtype=dtype)
                    E = torch.sigmoid(   torch.tensordot(noise, sigma.t(), [2], [0]).add(mu).mul(alpha)   ).mul(0.999999).add(0.0000005)
                                         ~~~~~~~~~~~~~~~ <--- HERE
                    logprob = E.log().mul(Ys).add((1.0 - E).log().mul(1.0 - Ys)).neg().sum(dim = 2).neg()
                    maxlogprob = logprob.max(dim = 0).values
`
The input arguments for torch.tensordot are incorrect.
My torch version is 1.10

**Comment by benjamindeneu** [comment]
Ok it seems that your python package on pip is not up-to-date as you removed tensordot in this commit 4bc95be0644de9afe9c5ee2931cf1de65e443fdf
I will try to install the lib from git instead !

**Comment by MaximilianPi** [comment]
Hi Benjamin,

yes, I removed tensordot because it had different interfaces depending on whether I was using torch.jit.script or not (torch.jit.script didn't support all of my family implementations). The einsum behaviour was consistent for all torch versions and the torch.jit stuff
