### ISSUE TITLE
Dependencies not found for windows

### ISSUE THREAD

**Issue by Zinco-Li** [TheoreticalEcology/s-jSDM#81]
I tried to install  automatically by "install_sjSDM(version = c("cpu"))",
such error arose: The following packages are not available from current channels:

  - python=3.1
  
Then I tried to install manually in cmd, but it seemed like that: 
library(sjSDM)
√ torch 
x torch_optimizer 
x pyro 
x madgrad

**Comment by MaximilianPi** [comment]
Hi @Zinco-Li,

it seems that the installation fails again 

for a hot fix, do:

1) restart RStudio
2) reticulate::conda_remove('r-reticulate')
3) reticulate::conda_create('r-reticulate', python_version='3.8')
4) reticulate::conda_install('r-reticulate',packages = c("pytorch", "torchvision", "torchaudio" ,"-c", "pytorch"))
5) reticulate::conda_install('r-reticulate',packages = c("pyro-ppl", "torch_optimizer", "madgrad"), pip=TRUE)
