### ISSUE TITLE
AIC function

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/s-jSDM#9]
I have implemented a logLik function in https://github.com/TheoreticalEcology/s-jSDM/commit/80c906bb24ed33eb8ff503428ec90226ce11305d ... question is if we should also implement an AIC ... I would tend towards not, because of the problem of counting df.

**Comment by MaximilianPi** [comment]
I will close this for now, with the regularization there is no need for the AIC, but maybe we should provide a vignette why regularization > model selection.
